# Generated by Django 3.0.1 on 2019-12-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('title', models.CharField(choices=[('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Postdoc Fellow', 'Postdoc Fellow'), ('Ph.D. Candidate', 'Ph.D. Candidate'), ('MPhil Candidate', 'MPhil Candidate'), ('Research Assistant', 'Research Assistant'), ('Alumni', 'Alumni')], max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('project', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('experience', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('headshot', models.ImageField(blank=True, null=True, upload_to='img/headshot')),
            ],
        ),
    ]
